---
apiVersion: v1
kind: Pod
metadata:
  name: extractor-test
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: extractor-test
    securityContext:
      privileged: false
    image: ccr.ccs.tencentyun.com/prometheus/extractor-test:latest
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c","sh run.sh"]
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 2000m
        memory: 3Gi
      limits:
        cpu: 2000m
        memory: 3Gi
    volumeMounts:
      - name: featuredb
        mountPath: /tmp/featuredb
  volumes:
    - name: featuredb
      hostPath:
        path: /mnt
  imagePullSecrets:
  - name: qcloudregistrykey
  securityContext:
    runAsUser: 0
