---
apiVersion: v1
kind: Pod
metadata:
  name: training-test8
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: training-test
    securityContext:
      privileged: false
    image: ccr.ccs.tencentyun.com/prometheus/training-test:latest
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c","sh run_training.sh --algo_id prebuild_v2 --download_feature_db true --do_preprocessing true"]
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 7000m
        memory: 27Gi
      limits:
        cpu: 7000m
        memory: 27Gi
    volumeMounts:
      - name: featuredb
        mountPath: /tmp/featuredb
  volumes:
    - name: featuredb
      hostPath:
        path: /mnt
  imagePullSecrets:
  - name: qcloudregistrykey
  securityContext:
    runAsUser: 0
